# Generated by Django 6.0.3 on 2026-04-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=300),
            preserve_default=False,
        ),
    ]
